POST http://localhost:3000/register
Content-Type: application/json

{
    "name":"konradudso",
    "email":"1d2e@gmail.com",
    "password":"1234567"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email":"xd@gmail.com",
    "password":"1234567"
}
###
GET  http://localhost:3000/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZjQ2YTBlOTBiNDJlMjg4Yzg5OWZjMyIsImlhdCI6MTYwOTg1MzQ1NH0.7rg0ZNQHiGkuwyaOTs02PmO9lGSwx0yHY0eYTHMhhmo